<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\VideoCall.Codecs\VideoCall.Codecs.csproj" />
    <ProjectReference Include="..\VideoCall.Media\VideoCall.Media.csproj" />
    <ProjectReference Include="..\VideoCall.Network\VideoCall.Network.csproj" />
    <ProjectReference Include="..\VideoCall.Protocol\VideoCall.Protocol.csproj" />
  </ItemGroup>

</Project>
